name: dingdong_flutter_teacher
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  http: ^1.2.2
  flutter_downloader: ^1.11.8
  url_launcher: ^6.3.1
  permission_handler: ^11.3.1
  intl: ^0.20.1
  provider: ^6.1.2
  dio: ^5.7.0
  image_picker: ^1.1.2
  file_picker: ^8.1.7
  path_provider: ^2.1.5
  flutter:
    sdk: flutter
  flutter_calendar_carousel: ^2.4.4
  table_calendar: ^3.0.6
  cupertino_icons: ^1.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/

